[project]
name = "s2-sr"
version = "0.1.0"
description = "Sentinel-2 MSI L2A download and processing"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gdal==3.4.3.*",
    "mpi4py>=4.1.0",
    "numpy<2",
    "pandas>=2.3.2",
    "requests>=2.32.5",
    "shapely>=2.1.1",
]
